### ISSUE TITLE
New spec: BLAKE3

### ISSUE THREAD

**Issue by veorq** [C2SP/C2SP#101]
/cc @C2SP/stewards

We would like to submit [BLAKE3](https://github.com/BLAKE3-team/BLAKE3), by adapting our [IETF draft](https://datatracker.ietf.org/doc/draft-aumasson-blake3/) to the C2SP format.

**Sales pitch**:
* BLAKE3 is the fastest cryptographic hash function used in practice (faster than SHA-3 and BLAKE2).
* It's not only a general-purpose hash but also a PRF, MAC, KDF, and XOF.
* Lot of projects use it: it has 5k+ GitHub stars, and major projects using BLAKE3 in production include LLVM, Bazel, OpenZFS, IPFS, and [apparently Tekken 8](https://twitter.com/rodarmor/status/1751567502050771189). We keep [an incomplete list on GitHub](https://github.com/BLAKE3-team/BLAKE3/?tab=readme-ov-file#adoption--deployment).

One of our motivations with this submission is to get BLAKE3 added to OpenSSL (which seems to require some formal validation).

**Proposed short name**: BLAKE3

**Proposed maintainers**: @veorq @oconnor663 @sneves @zooko

**Comment by FiloSottile** [comment]
> and [apparently Tekken 8](https://twitter.com/rodarmor/status/1751567502050771189)

Hard to argue with that :) Joke aside, BLAKE3 is a broadly used hash function and a specification for it would definitely be useful. Steward +1 from me.

**Comment by dconnolly** [comment]
++++

**Comment by FiloSottile** [comment]
With @dconnolly's +1 we have 2/3 steward quorum 🚢 

Per https://github.com/C2SP/C2SP/blob/main/.github/PLAYBOOKS.md#new-specification-playbook I created @C2SP/BLAKE3 and #103.

@veorq @oconnor663 @sneves and @zooko, welcome to C2SP and thank you for maintaining a spec!

You will have access to approve and merge any PR to your spec (both the .md file in the root of the repository and anything under a directory named like your spec), as well as to manage the issue tracker. Please only take maintainer actions on issues related to your spec.

Note that GitHub paths are not stable: please use the c2sp.org redirector when possible. c2sp.org/BLAKE3 redirects to your spec.

Let us know if you encounter any issues.

**Comment by oconnor663** [comment]
Thanks @FiloSottile and @dconnolly!

**Comment by veorq** [comment]
Thanks for the swift response! We'll start working on the draft.
