### ISSUE TITLE
STREAM construction

### ISSUE THREAD

**Issue by str4d** [C2SP/C2SP#2]
The STREAM construction for nOAE was originally described in Figure 10 of the paper [Online Authenticated-Encryption and its Nonce-Reuse Misuse-Resistance](https://eprint.iacr.org/2015/189.pdf). Since then, several concrete instantiations have arisen (notably [age](https://age-encryption.org/v1) and [Tink](https://developers.google.com/tink/streaming-aead)), that make slightly different design choices.

It would be great to specify these instantiations, both to collate the rationale for their choices, and to help guide people towards an existing instantiation in order to limit the proliferation of additional variants (which will make it easier for people to write STREAM implementations).

**Comment by tarcieri** [comment]
In the @RustCrypto `aead` crate I've been using the following nomenclature for two different STREAM variants:

- [StreamBE32](https://docs.rs/aead/0.4.2/aead/stream/struct.StreamBE32.html): the original “Rogaway-flavored” STREAM. Uses a 32-bit big endian counter and 1-byte “last block” flag stored as the last 5-bytes of the AEAD nonce.
- [StreamLE31](https://docs.rs/aead/0.4.2/aead/stream/struct.StreamLE31.html): STREAM as instantiated with a 31-bit little endian counter and 1-bit “last block” flag stored as the most significant bit of the counter when interpreted as a 32-bit integer. The 31-bit + 1-bit value is stored as the last 4 bytes of the AEAD nonce.

**Comment by tarcieri** [comment]
Note that I kind of regret those names, and think names like "STREAM32BE" and "STREAM31LE" might be a better choice. I'm happy to change the names in the `aead` crate to whatever is eventually defined in the spec.

Regardless I think it'd be nice to have qualified names which are unique and SEO-friendly in some way, as "STREAM" certainly is not.

**Comment by FiloSottile** [comment]
Given the current scattered state of the ecosystem, a good v0 would be a survey of deployed schemes that can't be readily changed (age v1, Tink, Miscreant, RustCrypto, libsodium, AWS SDK). A future v1 will either make (some of) them a specific profile of a generic construction, or will retain them informationally while steering new implementations towards a recommended scheme.

Discussing with @str4d, we agreed that `streaming-encryption` is a good slug for such a survey/umbrella specification.

ACK on inclusion of these specs; 1/3 towards steward quorum. I can volunteer as co-maintainer.

**Comment by tarcieri** [comment]
FYI: here's an updated paper on STREAM which analyzes Tink's use of HKDF (and also suggests some possible alternatives): https://eprint.iacr.org/2020/1019.pdf
