### ISSUE TITLE
New specs: note, checkpoint, witness, bastion

### ISSUE THREAD

**Issue by FiloSottile** [C2SP/C2SP#43]
This is a set of transparency log related specs.

_note_ is for the signed note format, and has a draft at https://github.com/C2SP/C2SP/blob/filippo/tlogs/note.md. Would be maintained by me and @rsc (if he wishes).

_checkpoint_ is for the signed tree head artifacts, and has a draft at https://github.com/C2SP/C2SP/blob/filippo/tlogs/checkpoint.md. It would be maintained by me.

_witness_ is for a protocol to communicate with cosigning witnesses. It has a draft at https://git.glasklar.is/sigsum/project/documentation/-/blob/ed872c8b04161aabf41ae6bbf2797e23dd7c332f/witness.md and https://git.glasklar.is/sigsum/project/documentation/-/blob/filippo/witness-apis/proposals/2023-08-witness-apis.md. It would be maintained by me, @rgdd, and Niels Möller.

_bastion_ is for a reverse proxy that allows exposing allow-listed services to the Internet. It has a draft at https://git.glasklar.is/sigsum/project/documentation/-/blob/ed872c8b04161aabf41ae6bbf2797e23dd7c332f/bastion.md. It would be maintained by me, @rgdd, and Niels Möller.

/cc @dconnolly @str4d for approval

**Comment by str4d** [comment]
I think `note`, `checkpoint`, and `witness` are too generic to use for spec shortnames. `tlog-note`, `tlog-checkpoint` and `tlog-witness` would be acceptable to me.

**Comment by FiloSottile** [comment]
`tlog-checkpoint` and `tlog-witness` make sense, although I'm not sure how likely it is we'll get in the future another `checkpoint` spec. `note` is not tlog-specific though, it's just a signed textual format.

**Comment by FiloSottile** [comment]
We reached consensus on the Sigsum side to move the following specs to C2SP (with renamings as requested for clarity, and as discussed with the C2SP stewards)

* signed-note
* tlog-checkpoint
* tlog-cosignature
* tlog-witness
* https-bastion

https://git.glasklar.is/sigsum/project/documentation/-/blob/main/proposals/2024-01-on-specifications-and-governance.md

The maintainers will be @FiloSottile, @rsc for signed-note, and @rgdd, @FiloSottile, TBD from the Google Trust Fabric team for the rest.

**Comment by str4d** [comment]
ACK on inclusion of these specs; with @FiloSottile's implicit approval as maintainer, we have steward quorum (2/3).
