### ISSUE TITLE
New spec: chacha8rand

### ISSUE THREAD

**Issue by FiloSottile** [C2SP/C2SP#44]
_chacha8rand_ is a spec for the new high-performance CSPRNG being built into Go 1.22.

There is a draft at #41.

It would be maintained by me and @rsc (if he wishes).

/cc @dconnolly @str4d for approval

**Comment by str4d** [comment]
ACK on inclusion of this spec; with @FiloSottile's implicit approval as maintainer, we have steward quorum (2/3).

Closed by #41 being merged (which included the `CODEOWNERS` change). For future new-spec issues we will close them (after reaching approval quorum) with a PR to make all necessary new-spec changes to the repo, including to `CODEOWNERS`, and then maintainers can open PRs with the spec content that do not make changes to `CODEOWNERS`.
