### ISSUE TITLE
New spec: XAES-256-GCM

### ISSUE THREAD

**Issue by FiloSottile** [C2SP/C2SP#45]
_XAES-256-GCM_ is a spec for an extended-nonce AEAD based on the composition of a standard NIST SP 800-108r1 KDF and the standard NIST AES-256-GCM AEAD.

The XAES-256-GCM inputs are a 256-bit key, a 192-bit nonce, a plaintext of up to approximately 64GiB, and additional data of up to 2 EiB.

Unlike AES-256-GCM, the XAES-256-GCM nonce can be randomly generated for a virtually unlimited number of messages. Only a 256-bit key version is specified, which provides a comfortable multi-user security margin.

XAES-256-GCM derives a subkey for use with AES-256-GCM from the input key and half the input nonce using a NIST SP 800-108r1 KDF. The derived key and the second half (last 96 bits) of the input nonce are used to encrypt the message with AES-256-GCM.

The KDF can be easily described as a sequence of three AES-256 invocations, but making it a profile of SP 800-108r1 allows a FIPS compliance argument.

There is a draft at #36.

It would be maintained by me.

/cc @dconnolly @str4d for approval

**Comment by str4d** [comment]
ACK on inclusion of this spec; with @FiloSottile's implicit approval as maintainer, we have steward quorum (2/3).
