### ISSUE TITLE
New spec assignment: sunlight

### ISSUE THREAD

**Issue by FiloSottile** [C2SP/C2SP#50]
Sunlight is a design for a new Certificate Transparency log server. The design includes a zero-merge-delay implementation (out of scope for this specification), and a new read-path API (what this specification is about).

Sunlight logs expose the regular RFC 6962 write APIs (add-chain, add-pre-chain, and get-roots), however all the read operations (get-sth, get-sth-consistency, get-proof-by-hash, get-entries, and get-entry-and-proof) are replaced with static assets served over HTTPS.

This specification is intended to document the precise names and formats of the assets made available by a Sunlight instance:

- the signed tree head in c2sp.org/tlog-checkpoint format
- the Merkle tree in tiles (research.swtch.com/tlog) format
- the tree leaves in compressed batches
- the list of roots and intermediates for chain building in PEM format

A complete design document (covering both implementation and new API) is available at https://filippo.io/a-different-CT-log.

**Comment by str4d** [comment]
ACK on inclusion of this spec; with @FiloSottile's implicit approval as proposer, we have steward quorum (2/3). Maintainer will be @FiloSottile.
