### ISSUE TITLE
signed-note: Support RSA as a signature type

### ISSUE THREAD

**Issue by haydentherapper** [C2SP/C2SP#63]
Sigstore will be using the tlog-cosignature and related specifications. Currently, our key hash

Private deployments have the option to use either ed25519, ecdsa or RSA for signature algorithms to maximize cryptographic agility. While the public deployment uses ECDSA, we don't provide any recommendations to private deployments.

The request is to include identifiers for RSA-PKCS#1-v1.5 and RSA-PSS. Within Sigstore deployments, the former is far more prevalent when RSA is used.

For key size and hash requirements, is it sufficient to include suggestions as SHOULDs? Ideally we don't need a signature type per combination of scheme, key size and hash. Tangential, but for ECDSA, should a preferred curve be included as a SHOULD?

Ref: https://github.com/C2SP/C2SP/pull/54#discussion_r1527628144

**Comment by haydentherapper** [comment]
It's just to maximize compatibility for self-hosted instances where there are existing PKIs. We can shift towards PSS as the recommendation when RSA is used, though it would be helpful to have PKCS#1 v1.5 specified still, even with a warning against using it.

**Comment by FiloSottile** [comment]
I am not familiar with self-hosted Sigstore. How does it reuse existing PKIs for the log signing key? (I can imagine how legacy signatures get logged *into* Sigstore, but why reuse an existing key as the signing key for a new log?)

Not trying to be difficult, but saddling the whole witness ecosystem with PKCS#1 v1.5 is something I would like to do only if strictly necessary.

**Comment by Foxboron** [comment]
I'm a bit unclear on how private sigstore instances are used, but is it relevant for *private* sigstore instances to interact with the witness ecosystem at large?

Is there cases where it could be useful for them to do so? I'd sorta imagine they would be publicly available if they where.

**Comment by AlCutter** [comment]
I share the reservations already expressed. 

> It's just to maximize compatibility for self-hosted instances where there are existing PKIs

I'm not aware of any log which relies on a PKI hierarchy for certifying its identity, for what I guess are obvious reasons given the need for CT, but perhaps you've come across rationale for why this would be necessary?

**Comment by haydentherapper** [comment]
What I meant was requirements to use a certain signature type due to one's organization, not reuse of a key. For example, if an organization uses only PKCS RSA keys in GCP or AWS, we want to meet them where they're at ideally. Cloud providers haven't mandated PSS so we still see users using both signature types.

@Foxboron, that's a good point that for private deployments that are private within an organization, I would not expect integration with a witness network. I also am referring to non-"rekor.sigstore.dev" deployments, which could be public. At some point, we hope to have more logs in the ecosystem for public artifacts.

What about supporting only PSS for now, and if we see a demand from users, we can revisit this later? It would cause the least friction to support both, but I understand the concerns.

**Comment by AlCutter** [comment]
I had a thought this morning, riffing on what Morton said above: since we're talking about private-only, non-public-interop instances of sigstore, those operators can do whatever they like, including just inventing IDs for whatever out-of-spec signature schemes they choose.

So: in acknowledgement of that, an option may be to add another signature scheme ID which is explicitly marked as "Reserved for internal, non-publicly-interoperable use" (the 192.168 of signature scheme IDs, if you like).

This would give space for private instances of things to do what they need without fear of a collision with any open-source code they might depend on, but also limits that use to private & internal settings as collisions with other private & internal instances on the interpretation of signatures with this ID are likely.

**Comment by FiloSottile** [comment]
> So: in acknowledgement of that, an option may be to add another signature scheme ID which is explicitly marked as "Reserved for internal, non-publicly-interoperable use" (the 192.168 of signature scheme IDs, if you like).

We have that! `0xFF`

> Reserved for signature types without an identifier byte assigned by this specification. It is RECOMMENDED that this byte be followed by a longer identifier that is unlikely to collide.

**Comment by Foxboron** [comment]
@haydentherapper 
> I also am referring to non-"rekor.sigstore.dev" deployments, which could be public. At some point, we hope to have more logs in the ecosystem for public artifacts.

My very non-strong opinion here is that if they are publicly available it doesn't make sense for the private provider of the public instance to use their existing PKI. They should rather use the algorithms the community wants.

I don't find this unreasonable personally, and with the `0xFF` identifier I suspect it should be fine?

**Comment by FiloSottile** [comment]
There is an argument against adding any additional algorithm in something that's implemented by a whole ecosystem (and really to anything, but let's focus on the ecosystem effects). Each and every client and witness implementation will need to add an RSA dependency, decide how to represent RSA keys (PKCS#1 format or PKCS#8?), deal with the bigger keys, respond to RSA vulnerabilities like the Marvin attack. Even further down the road we open up a potential debate on whether we should also have RSA cosignatures: after all if Ed25519 is not ok for signing, why is it ok for verifying? These are just the ones I can think off the top of my head.

"Let's front-load support for things we might need" is a very weak argument in favor of adding something. That's how you end up supporting everything, both the things you did need and the ones you did not.

I very much prefer to start without support for anything that's not needed now, and if the need materializes tomorrow we can add it tomorrow, with the advantage of knowing exactly what the need is. Maybe we add RSA-PSS now, and companies really need PKCS#1 v1.5, and we end up supporting both.

"No is temporary, yes is forever."

> What I meant was requirements to use a certain signature type due to one's organization, not reuse of a key. For example, if an organization uses only PKCS RSA keys in GCP or AWS, we want to meet them where they're at ideally.

Speaking of, is this organization someone you can ask more details to about their requirements?

In the meantime, I think `\xFFRSAPSS` is a perfectly fine ID for private instances. For public instances, I think it's worth having a conversation with the operator: if they are spinning up the instance as a public good, why can't they make it work like the main public instance, and not increase the ecosystem complexity?

**Comment by haydentherapper** [comment]
My view is that because this specification is brand new, there will be more focus on implementation and deployment of the spec now, so front-loading support for something we think we might need, and assuming it is not significant to support, mitigates risks of fracturing support in the ecosystem, e.g. a subset of witnesses do not support the newer algorithm because they do not frequently update. From what you've described, it seems like the cryptographic concerns are the primary motivator against RSA, so even if this is technically not difficult to add, the concern is it will be hard to maintain long-term.

For what it's worth, I'm speaking in generalities. I don't know of specific organizations that have requested RSA. I only represent an ecosystem where we have flexibility on which algorithm is used. Saying "there is a limited set of algorithms supported for public deployments joining the witness network" feels a bit odd, especially given RSA is very much still an industry staple.

> Even further down the road we open up a potential debate on whether we should also have RSA cosignatures: after all if Ed25519 is not ok for signing, why is it ok for verifying? 

Actually this was surprising to me too. I didn't realize we had restricted cosignatures to only ed25519. I would have expected that given checkpoints allow ECDSA in addition to ed25519, cosignatures would support both.

On this topic of checkpoints and RSA, I think this needs to be handled for the sunlight spec, lemme know if I should split this out into its own conversation. The [sunlight checkpoint](https://github.com/C2SP/C2SP/blob/main/sunlight.md#checkpoints) spec uses an identifier `0x05` to represent the signature type, without a suggestion of a specific algorithm. [RFC 6962](https://datatracker.ietf.org/doc/html/rfc6962#section-2.1.4) notes that signatures can be generated with ECDSA P-256 or RSA (rsassa-pkcs1-v1_5). If sunlight is following RFC 6962, then checkpoint verifiers will need to support verifying RSA. If not, then should sunlight be opinionated on the algorithm?
