### ISSUE TITLE
"Bug" in CODEOWNERS

### ISSUE THREAD

**Issue by real-or-random** [C2SP/C2SP#70]
GitHub is not happy with the recent changes in CODEOWNERS, see the yellow banner here: https://github.com/C2SP/C2SP/commit/489680478b87b5c3bc98a7cc20e29f4e2a28c4f8.

It reads: "make sure @gtank exists and has write access to the repository"

**Comment by gtank** [comment]
But...I do exist.

**Comment by FiloSottile** [comment]
You exist but you don't click invitations :) I resent it, plz accept.
