### ISSUE TITLE
New spec: tlog-tiles

### ISSUE THREAD

**Issue by FiloSottile** [C2SP/C2SP#77]
*tlog-tiles* is a spec describing how to expose generic transparency logs as static assets.

It specifies a set of assets exposed as GET requests: the checkpoint (per c2sp.org/tlog-checkpoing) for the tree head, tiles for the Merkle Tree, and entry bundles for the contents of the log.

It's extracted and made generic from the Go Checksum Database and the Sunlight spec. It's mostly compatible with those, and we'll adapt them to follow this spec.

There is a draft at #73.

It would be maintained by @AlCutter, @mhutchinson, and myself.

/cc @dconnolly @str4d for approval

**Comment by str4d** [comment]
ACK on inclusion of this spec; with @FiloSottile's implicit approval as proposer, we have steward quorum (2/3).
